#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""

@author: s1420671
"""

from netCDF4 import Dataset
import matplotlib.pyplot as plt
import numpy as np
import os



date = ['200401','200402','200403','200404','200405','200406','200407','200408',
        '200409','200410','200411','200412','200501','200502','200503','200504',
        '200505','200506','200507','200508','200509','200510','200511','200512',
        '200601','200602','200603','200604','200605','200606','200607','200608',
        '200609','200610','200611','200612','200701','200702','200703','200704',
        '200705','200706','200707','200708','200709','200710','200711','200712',
        '200801','200802','200803','200804','200805','200806','200807','200808',
        '200809','200810','200811','200812','200901','200902','200903','200904',
        '200905','200906','200907','200908','200909','200910','200911','200912',
        '201001','201002','201003','201004','201005','201006','201007','201008',
        '201009','201010','201011','201012','201101','201102','201103','201104',
        '201105','201106','201107','201108','201109','201110','201111','201112',
        '201201','201202','201203','201204','201205','201206','201207','201208',
        '201209','201210','201211','201212','201301','201302','201303','201304',
        '201305','201306','201307','201308','201309','201310','201311','201312',
        '201401','201402','201403','201404','201405','201406','201407','201408',
        '201409','201410','201411','201412','201501','201502','201503','201504',
        '201505','201506','201507','201508','201509','201510','201511','201512',
        '201601','201602','201603','201604','201605','201606','201607','201608',
        '201609','201610','201611','201612']



nmonths=len(date)
site = ['alt','brw','cgo',
        'kum','mhd','mlo',
        'nwr','smo','wlg','asc']

lati=[43,40,12,27,36,27,33,19,32,21]
loni=[23, 5,65, 5,34, 5,15, 2,56,33]
nsites = len(lati) 



os.chdir('/geos/d21/s1420671/12CH4/forward')
GC_12c=[]
#read in methane 12c data
for sitecount in np.arange(nsites):
    lat = lati[sitecount]
    lon = loni[sitecount]
    
    for n in range(len(datei)):
        methane_12c= 'out.{}01.nc'.format((str(datei[n])))
        fh = Dataset(methane_12c, mode='r')
        lons = fh.variables['LON'][:]
        lats = fh.variables['LAT'][:]   
        C12 = fh.variables['IJ-AVG-S__CH4'][:]
        fh.close()

        GC_12c = np.append(GC_12c, C12[0,lat,lon])
        
        

GC_c13=[]

#read in methane 13c data
for sitecount in np.arange(nsites):
    os.chdir('/geos/d21/s1420671/jacobian/13CH4/14yr/forward')
    lat = lati[sitecount]
    lon = loni[sitecount]
    for n in range(len(datei)):
        methane_13c= 'out.{}01.nc'.format((str(datei[n])))
        fh = Dataset(methane_13c, mode='r') 
        D = fh.variables['IJ-AVG-S__CH4'][:]
        fh.close()
        GC_c13 = np.append(GC_c13, D[0,lat,lon])
        

GC_pri=[]

#read in methane 13c data
for sitecount in np.arange(nsites):
    os.chdir('/geos/d21/s1420671/jacobian/13CH4/14yr/forward/allyears_prior/')
    lat = lati[sitecount]
    lon = loni[sitecount]
    for n in range(len(datei)):
        methane_13c= 'out.{}01.nc'.format((str(datei[n])))
        fh = Dataset(methane_13c, mode='r') 
        D = fh.variables['IJ-AVG-S__CH4'][:]
        fh.close()
        GC_pri = np.append(GC_pri, D[0,lat,lon])

  
d13pri = (((np.divide(GC_pri,GC_12c))/(0.0112372))-1)*1000
d13post = (((np.divide(GC_c13,GC_12c))/(0.0112372))-1)*1000


#NOAA values
mx=[]
y=[]

for siten in np.arange(len(site)):
    si = site[siten]
    os.chdir('/home/s1420671/Downloads/13CH4_NOAA_observations')
    f = open("ch4c13_"+si+"_surface-flask_1_sil_month.txt", "r")
    for line in f:
        if '2004' in line:
           mx = np.append(mx,line)         
        if '2005' in line:
           mx = np.append(mx,line)
        if '2006' in line:
           mx = np.append(mx,line)
        if '2007 ' in line:
           mx = np.append(mx,line)
        if '2008' in line:
           mx = np.append(mx,line)
        if '2009' in line:
           mx = np.append(mx,line)
        if '2010' in line:
           mx = np.append(mx,line)
        if '2011' in line:
           mx = np.append(mx,line)
        if '2012' in line:
           mx = np.append(mx,line)
        if '2013' in line:
           mx = np.append(mx,line)
        if '2014' in line:
           mx = np.append(mx,line)
        if '2015' in line:
            mx=np.append(mx,line)
        if '2016' in line:
           mx=np.append(mx,line)

    f.close


for line in mx:
    spl = line.split()
    
    y = np.append(y, float(spl[3]))



fig=plt.figure()
fig.set_figheight(30)
fig.set_figwidth(10)

import pandas as pd
x = pd.date_range(start='1/1/2004', end='1/1/2005', periods=nmonths)


scale=[]
pl=0

fig=plt.figure()
fig.set_figheight(20)
fig.set_figwidth(30)


for plot in np.arange(nsites):
    plt.rc('font', size=12)
    st =site[plot]
    ax=plt.subplot(4,5,plot+1)  
    plt.plot(x,d13pri[pl:pl+nmonths],x,d13post[pl:pl+nmonths],x, y[pl:pl+nmonths])
    plt.title(st,fontsize=12)

    plt.legend(('Prior', 'Posterior', 'NOAA'),prop={'size':10})
    pl=pl+nmonths

plt.subplots_adjust(hspace = 0.4)
